const colors = ref({
  normal: {
    name: "normal",
    displayName: "Normal",
    bg: "#121212",
    bgSecondary: "#1e1e24",
    buttonSecondary: "#2d2d3a",
    buttonPrimary: "#3a3a4c",
    buttonDanger: "#783838",
    textSecondary: "#d0d0d0",
    textPrimary: "#ffffff",
  },
  purple: {
    name: "purple",
    displayName: "Purple",
    bg: "#0b021a",
    bgSecondary: "#12032b",
    buttonSecondary: "#2B124C",
    buttonPrimary: "#522B5B",
    buttonDanger: "#854F6C",
    textSecondary: "#DFB6B2",
    textPrimary: "#FBE4D8",
  },
  orangeblue: {
    name: "orangeblue",
    displayName: "Orange Blue",
    bg: "#162037",
    bgSecondary: "#233154",
    buttonSecondary: "#FF9D77",
    buttonPrimary: "#e07e59",
    buttonDanger: "#d55d3a",
    textSecondary: "#ccdced",
    textPrimary: "#ffffff",
  },
  green: {
    name: "green",
    displayName: "Green",
    bg: "#051F20",
    bgSecondary: "#0B2B26",
    buttonSecondary: "#1d4740",
    buttonPrimary: "#163832",
    buttonDanger: "#235347",
    textSecondary: "#8EB69B",
    textPrimary: "#DAF1DE",
  },
  bluepurple: {
    name: "bluepurple",
    displayName: "Blue Purple",
    bg: "#0a1a38",
    bgSecondary: "#142747",
    buttonSecondary: "#C7A0BE",
    buttonPrimary: "#9d95d4",
    buttonDanger: "#9bb7da",
    textSecondary: "#d8e3f0",
    textPrimary: "#ffffff",
  },
  purpleblue: {
    name: "purpleblue",
    displayName: "Purple Blue",
    bg: "#1a2140",
    bgSecondary: "#263155",
    buttonSecondary: "#7d6c96",
    buttonPrimary: "#b99eb6",
    buttonDanger: "#dd8c90",
    textSecondary: "#b9c4d8",
    textPrimary: "#f0f5ff",
  },
});

export default colors;
