const colors = ref({
  normal: {
    name: "normal",
    displayName: "Normal",
    bg: "#000000",
    bgSecondary: "#130f21",
    buttonSecondary: "#272633",
    buttonPrimary: "#1c1c2e",
    buttonDanger: "#272633",
    textSecondary: "#bfbfbf",
    textPrimary: "#ffffff",
  },
  purple: {
    name: "purple",
    displayName: "Purple",
    bg: "#0b021a",
    bgSecondary: "#12032b",
    buttonSecondary: "#2B124C",
    buttonPrimary: "#522B5B",
    buttonDanger: "#854F6C",
    textSecondary: "#DFB6B2",
    textPrimary: "#FBE4D8",
  },
  orangeblue: {
    name: "orangeblue",
    displayName: "Orange Blue",
    bg: "#171c2f",
    bgSecondary: "#282f4f",
    buttonSecondary: "#FFA586",
    buttonPrimary: "#de8162",
    buttonDanger: "#c9542c",
    textSecondary: "#360a0f",
    textPrimary: "#ffffff",
  },
  green: {
    name: "green",
    displayName: "Green",
    bg: "#051F20",
    bgSecondary: "#0B2B26",
    buttonSecondary: "#1d4740",
    buttonPrimary: "#163832",
    buttonDanger: "#235347",
    textSecondary: "#8EB69B",
    textPrimary: "#DAF1DE",
  },
  bluepurple: {
    name: "bluepurple",
    displayName: "Blue Purple",
    bg: "#050d21",
    bgSecondary: "#0c1536",
    buttonSecondary: "#C38EB4",
    buttonPrimary: "#a49cd9",
    buttonDanger: "#86ABCF",
    textSecondary: "#13212e",
    textPrimary: "#8b9dad",
  },
  purpleblue: {
    name: "purpleblue",
    displayName: "Purple Blue",
    bg: "#181d30",
    bgSecondary: "#212f47",
    buttonSecondary: "#6C5E82",
    buttonPrimary: "#af91aa",
    buttonDanger: "#d37b80",
    textSecondary: "#3b4459",
    textPrimary: "#a1b0c9",
  },
});

export default colors;
